site_name: 勉強まとめ

# ページとmarkdownファイルを紐づける設定
nav:
  - 概要: 'index.md'
  - AWS: 'AWS/index.md'
  - GCP: 'GCP/index.md'

# ページのデザイン設定
theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# 検索機能の設定
extra:
  search:
    language: 'jp'

# 拡張機能の設定
markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - toc:
      permalink: true
  - pymdownx.tasklist:  
      custom_checkbox: true